version: "3.7"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.18.0/24

services:
  db:
    build:
      context: ./
      dockerfile: dockerfile-db
    image: db
    container_name: postgres
    environment:
      POSTGRES_MULTIPLE_DATABASES: oauth2, dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    #identify secret
    secrets:
    - db_password
    volumes:
    - ./db-data:/var/lib/postgres/data
    networks:
      default:
        ipv4_address: 172.18.18.13
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  keycloak:
    image: jboss/keycloak:9.0.0
    container_name: keycloak
    depends_on:
      - "db"
    command:
      [
        '-b',
        '0.0.0.0',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
        '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
        '-Djboss.socket.binding.port-offset=1000',
        '-Dkeycloak.profile.feature.upload_scripts=enabled',
      ]
    volumes:
    - ./realm-config:/opt/jboss/keycloak/realm-config
    - ./themes/adminlte:/opt/jboss/keycloak/themes/adminlte
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - KEYCLOAK_JDBC_PARAMS=ssl=false
    - DB_VENDOR=postgres
    - DB_ADDR=172.18.18.13
    - DB_PORT=5432
    - DB_DATABASE=oauth2
    - DB_SCHEMA=public
    - DB_USER=postgres
    - DB_PASSWORD=X22H9Fs4Y8TempPass
    - JDBC_PARAMS=useSSL=false
    ports:
    - 9080:9080
    - 9443:9443
    - 10990:10990
    networks:
      default:
        ipv4_address: 172.18.18.14
#just a comment
#directory to scripts
secrets:
  db_password:
    file: ./secrets/db_password.txt
  
